services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remitly-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: remitly-db
    environment:
      POSTGRES_DB: remitly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: remitly-migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path=/migrations", "-database=postgres://postgres:postgres@db:5432/remitly?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  db_data:
