services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remitly-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: remitly-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: remitly-migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path=/migrations", "-database=${DATABASE_URL}", "up"]
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  seed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remitly-seed
    volumes:
    - ./data:/data 
    env_file:
      - .env
    command: ["--seed"]
    depends_on:
      - db
      - migrate
    restart: "no"

volumes:
  db_data:
